"""Telegram Message Link Import worker & handlers (Telethon MTProto).

Allows authorized users to import videos/files from public or private Telegram channels
(including restricted channels with `noforwards` / Restrict Saving Content enabled) by
pasting the message link (e.g. `https://t.me/c/1234567890/42` or `https://t.me/channel/42`).

Runs the MTProto worker inside the watcher process (shares the Telethon worker.session).
The bot process inserts rows into `tg_import_jobs`, sends the initial progress message,
and the watcher worker downloads the media (including multi-file albums/media groups)
via Telethon MTProto chunk stream, saves it to staging, and hands it off to `upload_jobs`
to be uploaded to the user's storage channel.
"""

import asyncio
import html
import os
import re
import shutil
import time
from typing import List, Optional, Tuple

import httpx
from telethon.errors import FloodError

from bot_config import (
    BOT_TOKEN,
    DRIVE_SPLIT_PART_MB,
    PIKPAK_MAX_BYTES,
    PIKPAK_STAGING_DIR,
    TELEGRAM_API_URL,
    log,
)
from tg_helpers import parse_caption, human_size, format_eta as _fmt_eta, MEDIA_EXTS as _MEDIA_EXTS

POLL_INTERVAL = 3
PROGRESS_THROTTLE_S = 4.0
DB_THROTTLE_S = 5.0

TG_LINK_RE = re.compile(
    r"(?:https?://)?t\.me/(?:c/(\d+)|([a-zA-Z0-9_]+))/(?:(\d+)/)?(\d+)(?:-(\d+))?"
)


class TgImportError(Exception):
    """User-facing import failure message."""


def _is_media(fname: str) -> bool:
    return os.path.splitext(fname)[1].lower() in _MEDIA_EXTS


def parse_tg_links(text: str) -> List[dict]:
    """Parse text for Telegram message links. Returns list of parsed targets."""
    results = []
    seen = set()
    for m in TG_LINK_RE.finditer(text):
        raw_c = m.group(1)
        username = m.group(2)
        if raw_c:
            target_chat = f"-100{raw_c}"
        else:
            target_chat = username

        start_msg_id = int(m.group(4))
        end_msg_id = int(m.group(5)) if m.group(5) else start_msg_id

        if end_msg_id < start_msg_id:
            end_msg_id = start_msg_id
        end_msg_id = min(end_msg_id, start_msg_id + 50)

        for mid in range(start_msg_id, end_msg_id + 1):
            key = (target_chat, mid)
            if key not in seen:
                seen.add(key)
                results.append({
                    "target_chat": target_chat,
                    "target_msg_id": mid,
                    "raw_link": m.group(0),
                })
    return results


def parse_import_command(text: str) -> Tuple[List[dict], Optional[str], Optional[str]]:
    """Parse /import command line.

    Syntax: /import <link> [Custom Title] [| tag1, tag2]
    Returns (targets, custom_title, custom_tags).
    """
    cleaned = text.strip()
    for prefix in ("/import", "/save", "/dl", "/link"):
        if cleaned.lower().startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
            break

    links = parse_tg_links(cleaned)
    if not links:
        return [], None, None

    leftover = TG_LINK_RE.sub("", cleaned).strip()
    title = None
    tags = None

    if leftover:
        if "|" in leftover:
            parts = leftover.split("|", 1)
            title = parts[0].strip() or None
            tags = ", ".join(t.strip() for t in parts[1].split(",") if t.strip()) or None
        else:
            title = leftover.strip() or None

    return links, title, tags


# ---------------------------------------------------------------------------
# Schema / migrations
# ---------------------------------------------------------------------------
async def ensure_schema(db):
    """Ensure tg_import_jobs table and triggers exist; reset stalled running jobs on boot."""
    await db.execute("""
        CREATE TABLE IF NOT EXISTS tg_import_jobs (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            link          TEXT NOT NULL,
            target_chat   TEXT NOT NULL,
            target_msg_id BIGINT NOT NULL,
            chat_id       BIGINT,
            message_id    BIGINT,
            filename      TEXT,
            title         TEXT,
            tags          TEXT,
            size          BIGINT NOT NULL DEFAULT 0,
            status        TEXT NOT NULL DEFAULT 'queued'
                            CHECK (status IN ('inspecting','inspect_running','inspected','inspect_failed','queued','running','downloading','downloaded','uploading','done','failed','cancelled')),
            progress      INTEGER NOT NULL DEFAULT 0,
            speed         TEXT,
            error         TEXT,
            upload_id     BIGINT,
            created_at    TEXT NOT NULL DEFAULT now_text(),
            updated_at    TEXT NOT NULL DEFAULT now_text()
        )
    """)
    try:
        await db.execute("ALTER TABLE tg_import_jobs DROP CONSTRAINT IF EXISTS tg_import_jobs_status_check")
        await db.execute("""
            ALTER TABLE tg_import_jobs ADD CONSTRAINT tg_import_jobs_status_check
            CHECK (status IN ('inspecting','inspect_running','inspected','inspect_failed','queued','running','downloading','downloaded','uploading','done','failed','cancelled'))
        """)
    except Exception as e:
        log.debug("Constraint update for tg_import_jobs status: %s", e)

    await db.execute("CREATE INDEX IF NOT EXISTS idx_tg_import_jobs_status ON tg_import_jobs(status)")
    await db.execute("""
        CREATE OR REPLACE FUNCTION notify_tg_import_change() RETURNS trigger
        LANGUAGE plpgsql AS $func$ BEGIN
        PERFORM pg_notify('tg_import_changed', TG_TABLE_NAME); RETURN NULL; END $func$
    """)
    await db.execute("DROP TRIGGER IF EXISTS trg_notify_tg_import_jobs ON tg_import_jobs")
    await db.execute("""
        CREATE TRIGGER trg_notify_tg_import_jobs AFTER INSERT OR UPDATE OR DELETE ON tg_import_jobs
        FOR EACH STATEMENT EXECUTE FUNCTION notify_tg_import_change()
    """)
    await db.execute("""
        UPDATE tg_import_jobs
        SET status='queued', progress=0, updated_at=now_text()
        WHERE status IN ('running', 'downloading')
    """)
    await db.execute("""
        UPDATE tg_import_jobs
        SET status='cancelled', error='Aborted on restart', updated_at=now_text()
        WHERE status IN ('inspecting', 'inspect_running')
    """)


# ---------------------------------------------------------------------------
# Worker & message editing
# ---------------------------------------------------------------------------
async def _safe_edit(chat_id: Optional[int], message_id: Optional[int], text: str, kb=None):
    """Edit Telegram message via Bot API HTTP without crashing on failures."""
    if not chat_id or not message_id or not BOT_TOKEN:
        return
    base_url = (TELEGRAM_API_URL or "https://api.telegram.org").rstrip("/")
    url = f"{base_url}/bot{BOT_TOKEN}/editMessageText"
    payload = {
        "chat_id": chat_id,
        "message_id": message_id,
        "text": text,
        "parse_mode": "HTML",
    }
    if kb:
        payload["reply_markup"] = kb
    try:
        async with httpx.AsyncClient(timeout=10.0) as cli:
            await cli.post(url, json=payload)
    except Exception as e:
        log.debug("Failed to edit tg_import progress msg (%s, %s): %s", chat_id, message_id, e)


async def _claim_next(db):
    rs = await db.execute("""
        UPDATE tg_import_jobs
        SET status='running', updated_at=now_text()
        WHERE id = (
            SELECT id FROM tg_import_jobs
            WHERE status='queued'
            ORDER BY id ASC
            LIMIT 1
            FOR UPDATE SKIP LOCKED
        )
        RETURNING id, link, target_chat, target_msg_id, chat_id, message_id, title, tags
    """)
    if not rs.rows:
        return None
    r = rs.rows[0]
    return {
        "id": r[0],
        "link": r[1],
        "target_chat": r[2],
        "target_msg_id": r[3],
        "chat_id": r[4],
        "message_id": r[5],
        "title": r[6],
        "tags": r[7],
    }


async def _is_cancelled(db, jid: int) -> bool:
    rs = await db.execute("SELECT status FROM tg_import_jobs WHERE id=?", [jid])
    if rs.rows and rs.rows[0][0] == "cancelled":
        return True
    return False


async def _download_part_stream(client, msg, dst_path, on_progress=None):
    """Download message media using iter_download with flood-wait retry and byte progress."""
    offset = 0
    total_size = int(getattr(msg.file, "size", 0) or 0)
    with open(dst_path, "wb") as f:
        stuck_count = 0
        last_offset = 0
        while True:
            try:
                async for chunk in client.iter_download(msg.media, offset=offset, request_size=512 * 1024):
                    f.write(chunk)
                    offset += len(chunk)
                    if on_progress:
                        await on_progress(offset, total_size)
                return
            except FloodError as e:
                stuck_count = stuck_count + 1 if offset == last_offset else 0
                last_offset = offset
                if stuck_count > 30:
                    raise TgImportError("Telegram flood-limited the download and progress halted.")
                wait_sec = int(getattr(e, "seconds", 10) or 10) + 1
                log.warning("Telethon download flood wait %ss at offset %s", wait_sec, offset)
                await asyncio.sleep(wait_sec)
                f.seek(offset)


def _speed_str(nbytes: float, secs: float) -> str:
    return (human_size(nbytes / secs).replace(" ", "") + "/s") if secs > 0 and nbytes >= 0 else ""


def _sanitize_filename(name: str) -> str:
    cleaned = re.sub(r'[\/\\:\*\?"<>\|]', "_", name).strip()
    return cleaned or "media_file"


def _derive_title_tags(caption_text: str, custom_title: Optional[str], custom_tags: Optional[str]) -> Tuple[str, str]:
    """Default Title/Tags from a source caption, mirroring the forward path
    (bot.py: parse_caption contract first, else derive_media_meta semantics):
    a contract caption supplies title+tags; any free-form caption contributes
    its hashtags as tags and its hashtag-free first line as the title — even
    when a custom Title was supplied."""
    title, tags = custom_title, custom_tags

    parsed = parse_caption(caption_text)
    if parsed:
        if not title:
            title = parsed["title"]
        if not tags:
            tags = ", ".join(parsed["tags"])
    elif caption_text:
        hash_tags = [t.lstrip("#") for t in re.findall(r"#\w+", caption_text)]
        if not tags and hash_tags:
            tags = ", ".join(hash_tags)
        if not title:
            first = re.sub(r"#\w+", "", caption_text.splitlines()[0]).strip(" -|")
            title = first[:120] or None
    return title or "", tags or ""


async def _track_upload_jobs(db, jid: int, upload_ids: List[int], chat_id: Optional[int], msg_id: Optional[int], title: str, size: int, tags: str, dst_dir: str):
    """Poll upload_jobs until all parts complete, then mark tg_import_job done and clean staging."""
    if not upload_ids:
        shutil.rmtree(dst_dir, ignore_errors=True)
        return

    state = {"last_edit": 0.0}
    total_jobs = len(upload_ids)

    for _ in range(4 * 3600 // 5):  # poll up to ~4h
        await asyncio.sleep(5)
        try:
            placeholders = ",".join("?" for _ in upload_ids)
            rs = await db.execute(
                f"SELECT id, status, message FROM upload_jobs WHERE id IN ({placeholders})",
                upload_ids,
            )
        except Exception:
            continue

        if not rs.rows:
            continue

        rows_by_id = {r[0]: {"status": r[1], "message": r[2]} for r in rs.rows}

        # Check if any upload job failed or was canceled
        failed_job = next((j for j in rows_by_id.values() if j["status"] in ("error", "canceled")), None)
        if failed_job:
            # Do NOT rmtree dst_dir here: sibling uploads and still-running downloads
            # share it. Every staged dir carries cleanup_source=1, so the watcher
            # frees each item's disk when its own job ends (even on error); the
            # remaining items simply finish flowing through the pipeline.
            err_detail = failed_job.get("message") or f"upload {failed_job['status']}"
            await db.execute(
                "UPDATE tg_import_jobs SET status='failed', error=?, updated_at=now_text() WHERE id=?",
                [err_detail[:400], jid],
            )
            await _safe_edit(
                chat_id, msg_id,
                f"❌ <b>Upload ke Telegram gagal:</b>\n{html.escape(err_detail[:300])}\n"
                f"<i>File lain pada impor ini tetap dilanjutkan.</i>",
            )
            return

        # Check if all upload jobs finished successfully
        done_count = sum(1 for j in rows_by_id.values() if j["status"] == "done")
        if done_count == total_jobs:
            shutil.rmtree(dst_dir, ignore_errors=True)
            await db.execute(
                "UPDATE tg_import_jobs SET status='done', progress=100, updated_at=now_text() WHERE id=?",
                [jid],
            )
            item_desc = f" ({total_jobs} files)" if total_jobs > 1 else ""
            success_text = (
                f"🎉 <b>Berhasil diimpor ke Cloud Drive!</b>\n\n"
                f"📁 <b>Title:</b> <code>{html.escape(title)}</code>{item_desc}\n"
                f"📊 <b>Size:</b> <code>{human_size(size)}</code>\n"
                f"🏷 <b>Tags:</b> <code>{html.escape(tags or '-')}</code>"
            )
            await _safe_edit(chat_id, msg_id, success_text)
            log.info("tg_import job #%s complete (all %s upload jobs done)", jid, total_jobs)
            return

        now = time.monotonic()
        if now - state["last_edit"] >= 10:
            state["last_edit"] = now
            running_job = next((j for j in rows_by_id.values() if j["status"] == "running"), None)
            detail = running_job.get("message") if running_job else None
            batch_note = f" (File {done_count + 1}/{total_jobs})" if total_jobs > 1 else ""
            status_text = (
                f"⬆️ <b>Menyimpan ke Cloud Drive:</b>\n"
                f"• <b>{html.escape(title)}</b>{batch_note}\n"
            )
            if detail:
                status_text += f"• <code>{html.escape(detail)}</code>"
            await _safe_edit(chat_id, msg_id, status_text)


async def _process(client, db, job):
    jid = job["id"]
    chat_id = job["chat_id"]
    msg_id = job["message_id"]
    target_chat = job["target_chat"]
    target_msg_id = job["target_msg_id"]
    custom_title = job["title"]
    custom_tags = job["tags"]

    cancel_kb = {
        "inline_keyboard": [
            [{"text": "✖️ Cancel Import", "callback_data": f"tgi_cancel_ask:{jid}"}]
        ]
    }

    dst_dir = os.path.join(PIKPAK_STAGING_DIR, f"tgimport_{jid}")
    t_start = time.monotonic()
    state = {
        "last_edit": 0.0,
        "last_db": 0.0,
        "t0": t_start,
        "spd_t": t_start,
        "spd_bytes": 0,
        "spd_str": "",
        "eta_str": "...",
    }

    try:
        if await _is_cancelled(db, jid):
            return

        await _safe_edit(chat_id, msg_id, f"🔍 <b>Mengambil informasi pesan…</b>\n<code>{target_chat} / {target_msg_id}</code>", kb=cancel_kb)

        # 1. Resolve entity & get message
        try:
            try:
                chat_entity = int(target_chat)
            except ValueError:
                chat_entity = target_chat
            entity = await client.get_entity(chat_entity)
            msg = await client.get_messages(entity, ids=target_msg_id)
        except Exception as e:
            err_str = str(e)
            if "ChannelPrivateError" in err_str or "Could not find the input entity" in err_str:
                raise TgImportError("Akun worker belum bergabung (join) ke channel/grup privat tersebut.")
            raise TgImportError(f"Gagal mengakses pesan: {err_str}")

        if not msg:
            raise TgImportError(f"Pesan ID {target_msg_id} tidak ditemukan.")
        if not msg.media:
            raise TgImportError(f"Pesan ID {target_msg_id} tidak memiliki file / video / media untuk diunduh.")

        # Check if this message is part of an album / media group
        messages_to_fetch = [msg]
        if getattr(msg, "grouped_id", None):
            try:
                min_id = max(1, target_msg_id - 15)
                max_id = target_msg_id + 15
                surrounding = await client.get_messages(entity, min_id=min_id, max_id=max_id)
                album_msgs = [m for m in surrounding if getattr(m, "grouped_id", None) == msg.grouped_id and m.media]
                if not any(m.id == msg.id for m in album_msgs):
                    album_msgs.append(msg)
                album_msgs.sort(key=lambda m: m.id)
                if len(album_msgs) > 1:
                    messages_to_fetch = album_msgs
                    log.info("Detected album with %s items for msg %s", len(album_msgs), target_msg_id)
            except Exception as e:
                log.warning("Album check failed for msg %s: %s", target_msg_id, e)

        # 2. Extract metadata & Caption — defaults mirror the forward path (see
        #    _derive_title_tags); filename / message-date as the last resort.
        caption_text = ""
        for m in messages_to_fetch:
            if m.message and m.message.strip():
                caption_text = m.message.strip()
                break

        title, tags = _derive_title_tags(caption_text, custom_title, custom_tags)
        if not title:
            first_fname = getattr(messages_to_fetch[0].file, "name", None)
            title = (os.path.splitext(first_fname)[0] if first_fname
                     else f"Media {messages_to_fetch[0].date:%Y-%m-%d}")

        # 3. Create staging destination (clean any stale files from previous attempts)
        shutil.rmtree(dst_dir, ignore_errors=True)
        os.makedirs(dst_dir, exist_ok=True)
        total_batch_size = sum(int(getattr(m.file, "size", 0) or getattr(m, "size", 0) or 0) for m in messages_to_fetch)
        first_fname = getattr(messages_to_fetch[0].file, "name", None) or f"item_{target_msg_id}.mp4"

        await db.execute(
            "UPDATE tg_import_jobs SET status='downloading', filename=?, title=?, tags=?, size=?, updated_at=now_text() WHERE id=?",
            [first_fname if len(messages_to_fetch) == 1 else f"Album ({len(messages_to_fetch)} files)", title, tags, total_batch_size, jid],
        )

        # 4+5. Pipelined per file: download → validate → enqueue upload job immediately,
        # so the watcher uploads this file while the next one is still downloading.
        # Peak staging disk ≈ one in-flight download instead of the whole album.
        multi_file = len(messages_to_fetch) > 1
        upload_ids = []
        batch_done_base = 0
        for idx, m in enumerate(messages_to_fetch, start=1):
            m_fname = getattr(m.file, "name", None)
            if not m_fname:
                ext = getattr(m.file, "ext", None) or ".mp4"
                if not ext.startswith("."):
                    ext = f".{ext}"
                if m.video:
                    m_fname = f"video_{m.id}{ext}"
                elif m.photo:
                    m_fname = f"photo_{m.id}.jpg"
                elif m.audio or m.voice:
                    m_fname = f"audio_{m.id}{ext}"
                else:
                    m_fname = f"file_{m.id}{ext}"
            else:
                m_fname = _sanitize_filename(m_fname)

            target_path = os.path.join(dst_dir, m_fname)
            if os.path.exists(target_path):
                target_path = os.path.join(dst_dir, f"{idx}_{m_fname}")

            m_size = int(getattr(m.file, "size", 0) or getattr(m, "size", 0) or 0)

            async def on_progress(done_bytes, _part_total, current_idx=idx, total_items=len(messages_to_fetch), fname=m_fname):
                now = time.monotonic()
                if now - state.get("last_cancel", 0.0) >= 2.0:
                    state["last_cancel"] = now
                    if await _is_cancelled(db, jid):
                        raise asyncio.CancelledError("Import cancelled by user")

                overall_done = batch_done_base + done_bytes
                total = total_batch_size or 1
                pct = min(100, int(overall_done * 100 / total))

                # Rolling-window speed (every >= 2.0s) & session average ETA (PikPak worker pattern)
                dt = now - state["spd_t"]
                if dt >= 2.0:
                    dn = overall_done - state["spd_bytes"]
                    state["spd_str"] = _speed_str(dn, dt)
                    state["spd_bytes"] = overall_done
                    state["spd_t"] = now

                    sess_dt = now - state["t0"]
                    if sess_dt > 10 and overall_done > 0 and total > overall_done:
                        avg_rate = overall_done / sess_dt
                        state["eta_str"] = _fmt_eta((total - overall_done) / avg_rate)
                    else:
                        state["eta_str"] = "..."

                spd_text = state["spd_str"]
                eta_text = state["eta_str"]

                if now - state["last_db"] >= DB_THROTTLE_S:
                    state["last_db"] = now
                    spd_eta = f"{spd_text} · ETA {eta_text}".strip(" ·") if spd_text else ""
                    await db.execute(
                        "UPDATE tg_import_jobs SET progress=?, speed=?, updated_at=now_text() WHERE id=?",
                        [pct, spd_eta, jid],
                    )

                if now - state["last_edit"] >= PROGRESS_THROTTLE_S:
                    state["last_edit"] = now
                    item_note = f" (File {current_idx}/{total_items})" if total_items > 1 else ""
                    spd_line = f"• Speed: <code>{spd_text}</code> · ETA <code>{eta_text}</code>" if spd_text else "• Speed: <i>menghitung…</i>"
                    edit_text = (
                        f"⬇️ <b>Downloading from Telegram:</b>\n"
                        f"• File: <code>{html.escape(fname)}</code>{item_note}\n"
                        f"• Progress: <code>{pct}%</code> ({human_size(overall_done)} / {human_size(total)})\n"
                        f"{spd_line}"
                    )
                    await _safe_edit(chat_id, msg_id, edit_text, kb=cancel_kb)

            await _download_part_stream(client, m, target_path, on_progress)
            batch_done_base += m_size

            # Size validation + immediate hand-off of THIS file (pipeline step).
            real_size = os.path.getsize(target_path)
            if real_size <= 0:
                raise TgImportError(f"File selesai diunduh tetapi kosong: {m_fname}")
            kind = "media" if _is_media(m_fname) else "archive"
            part_size = DRIVE_SPLIT_PART_MB if real_size > PIKPAK_MAX_BYTES else 4096
            if multi_file:
                # Own single-item subfolder so the watcher's cleanup_source=1 frees
                # this file's disk as soon as its own upload job ends.
                sub_dir = os.path.join(dst_dir, f"item_{idx}")
                os.makedirs(sub_dir, exist_ok=True)
                shutil.move(target_path, os.path.join(sub_dir, m_fname))
                source_path, item_title = sub_dir, f"{title} (Part {idx})"
            else:
                source_path, item_title = dst_dir, title

            rs = await db.execute(
                "INSERT INTO upload_jobs (kind, title, tags, source_path, part_size, origin, cleanup_source, total_bytes, status) "
                "VALUES (?, ?, ?, ?, ?, 'upload', 1, ?, 'pending') RETURNING id",
                [kind, item_title, tags, source_path, part_size, real_size],
            )
            if rs.rows:
                upload_ids.append(rs.rows[0][0])

        if not upload_ids:
            raise TgImportError("Download selesai tetapi tidak ada file yang tersimpan.")

        last_upload_id = upload_ids[-1] if upload_ids else None
        await db.execute(
            "UPDATE tg_import_jobs SET status='uploading', upload_id=?, progress=100, updated_at=now_text() WHERE id=?",
            [last_upload_id, jid],
        )

        await _safe_edit(
            chat_id, msg_id,
            f"⬆️ <b>Menyimpan ke Cloud Drive:</b>\n"
            f"• Title: <b>{html.escape(title)}</b>\n"
            f"• Total Files: <code>{len(upload_ids)} file(s)</code>\n"
            f"• Total Size: <code>{human_size(total_batch_size)}</code>\n"
            f"<i>Sedang diproses oleh watcher (upload/segmentasi jika &gt;2GB)…</i>"
        )

        asyncio.create_task(_track_upload_jobs(db, jid, upload_ids, chat_id, msg_id, title, total_batch_size, tags, dst_dir))

    except (asyncio.CancelledError, TgImportError) as e:
        shutil.rmtree(dst_dir, ignore_errors=True)
        err_msg = str(e) or "Dibatalkan"
        await db.execute(
            "UPDATE tg_import_jobs SET status='failed', error=?, updated_at=now_text() WHERE id=?",
            [err_msg[:400], jid],
        )
        await _safe_edit(chat_id, msg_id, f"❌ <b>Import Gagal:</b>\n{html.escape(err_msg)}")
    except Exception as e:
        log.exception("Unexpected error in tg_import job #%s", jid)
        shutil.rmtree(dst_dir, ignore_errors=True)
        err_msg = str(e)
        await db.execute(
            "UPDATE tg_import_jobs SET status='failed', error=?, updated_at=now_text() WHERE id=?",
            [err_msg[:400], jid],
        )
        await _safe_edit(chat_id, msg_id, f"❌ <b>Import Error:</b>\n{html.escape(err_msg[:300])}")


async def inspect_message_meta(client, target_chat: str, target_msg_id: int) -> dict:
    """Inspect a message via Telethon MTProto to extract caption, auto title/tags, filename, and size."""
    try:
        try:
            chat_entity = int(target_chat)
        except ValueError:
            chat_entity = target_chat
        entity = await client.get_entity(chat_entity)
        msg = await client.get_messages(entity, ids=target_msg_id)
    except Exception as e:
        err_str = str(e)
        if "ChannelPrivateError" in err_str or "Could not find the input entity" in err_str:
            return {"ok": False, "error": "Akun worker belum bergabung (join) ke channel/grup privat tersebut."}
        return {"ok": False, "error": f"Gagal mengakses pesan: {err_str}"}

    if not msg:
        return {"ok": False, "error": f"Pesan ID {target_msg_id} tidak ditemukan."}
    if not msg.media:
        return {"ok": False, "error": f"Pesan ID {target_msg_id} tidak memiliki file / video / media untuk diunduh."}

    messages_to_fetch = [msg]
    if getattr(msg, "grouped_id", None):
        try:
            min_id = max(1, target_msg_id - 15)
            max_id = target_msg_id + 15
            surrounding = await client.get_messages(entity, min_id=min_id, max_id=max_id)
            album_msgs = [m for m in surrounding if getattr(m, "grouped_id", None) == msg.grouped_id and m.media]
            if not any(m.id == msg.id for m in album_msgs):
                album_msgs.append(msg)
            album_msgs.sort(key=lambda m: m.id)
            if len(album_msgs) > 1:
                messages_to_fetch = album_msgs
        except Exception as e:
            log.warning("Album check failed during inspect for msg %s: %s", target_msg_id, e)

    caption_text = ""
    for m in messages_to_fetch:
        if m.message and m.message.strip():
            caption_text = m.message.strip()
            break

    title, tags = _derive_title_tags(caption_text, None, None)
    if not title:
        first_fname = getattr(messages_to_fetch[0].file, "name", None)
        title = (os.path.splitext(first_fname)[0] if first_fname
                 else f"Media {messages_to_fetch[0].date:%Y-%m-%d}")

    total_batch_size = sum(int(getattr(m.file, "size", 0) or getattr(m, "size", 0) or 0) for m in messages_to_fetch)
    first_fname = getattr(messages_to_fetch[0].file, "name", None)
    if not first_fname:
        first_fname = f"Album ({len(messages_to_fetch)} files)" if len(messages_to_fetch) > 1 else f"item_{target_msg_id}.mp4"

    return {
        "ok": True,
        "title": title,
        "tags": tags,
        "filename": first_fname if len(messages_to_fetch) == 1 else f"Album ({len(messages_to_fetch)} files)",
        "size": total_batch_size,
        "num_files": len(messages_to_fetch),
    }


async def _process_inspection(client, db, job_id: int, target_chat: str, target_msg_id: int):
    try:
        res = await inspect_message_meta(client, target_chat, target_msg_id)
        if res.get("ok"):
            await db.execute(
                "UPDATE tg_import_jobs SET status='inspected', filename=?, size=?, title=?, tags=?, updated_at=now_text() WHERE id=?",
                [res["filename"], res["size"], res["title"], res["tags"], job_id],
            )
            log.info("Inspected tg_import job #%s: title='%s', tags='%s', file='%s', size=%s", job_id, res["title"], res["tags"], res["filename"], res["size"])
        else:
            await db.execute(
                "UPDATE tg_import_jobs SET status='inspect_failed', error=?, updated_at=now_text() WHERE id=?",
                [res.get("error", "Inspection failed")[:400], job_id],
            )
            log.warning("Inspect failed for tg_import job #%s: %s", job_id, res.get("error"))
    except Exception as e:
        log.exception("Unexpected error inspecting tg_import job #%s", job_id)
        await db.execute(
            "UPDATE tg_import_jobs SET status='inspect_failed', error=?, updated_at=now_text() WHERE id=?",
            [str(e)[:400], job_id],
        )


async def _poll_inspections(client, db):
    """Check for pending inspection requests and dispatch them concurrently."""
    try:
        rs = await db.execute("SELECT id, target_chat, target_msg_id FROM tg_import_jobs WHERE status='inspecting' ORDER BY id ASC")
        for r in rs.rows:
            jid, t_chat, t_mid = r[0], r[1], r[2]
            claim = await db.execute("UPDATE tg_import_jobs SET status='inspect_running', updated_at=now_text() WHERE id=? AND status='inspecting' RETURNING id", [jid])
            if claim.rows:
                asyncio.create_task(_process_inspection(client, db, jid, t_chat, t_mid))
    except Exception as e:
        log.debug("Error checking tg_import inspections: %s", e)


async def _inspection_loop(client, db):
    while True:
        await _poll_inspections(client, db)
        await asyncio.sleep(0.2)


async def worker_loop(client, db):
    """Background worker loop in watcher.py for tg_import jobs."""
    log.info("Telegram link import worker started")
    inspect_task = asyncio.create_task(_inspection_loop(client, db))
    try:
        while True:
            try:
                job = await _claim_next(db)
                if job:
                    await _process(client, db, job)
                else:
                    await asyncio.sleep(POLL_INTERVAL)
            except Exception as e:
                log.exception("tg_import worker loop error: %s", e)
                await asyncio.sleep(POLL_INTERVAL)
    finally:
        inspect_task.cancel()
