"""Archive-unpack worker — extract a stored multi-part archive item and re-store its contents as
normal (streamable) items, so e.g. a video inside a password-protected 7z can be watched in-app
without downloading the whole archive locally.

Runs INSIDE the watcher process (the only one with both the Telethon client and p7zip). The web
inserts an `unpack_jobs` row (item_id + optional password); this worker:
  1. claims the job and SCRUBS the password — reads it into a local var and NULLs the column in the
     same statement, so it never lingers in the DB (only the seconds between insert and claim),
  2. downloads every part of the item from Telegram and concatenates them in part order → the archive
     (plain ordered concat reconstructs both 7z-native multi-volumes and raw binary splits),
  3. 7z-extracts it (with the password if encrypted; `-p` is always passed so 7z never blocks on an
     interactive prompt),
  4. inserts one `upload_jobs` row per extracted file (origin='upload', cleanup_source=1) → the
     existing watcher pipeline uploads them and the bot indexes them (video → streamable media item),
  5. keeps the original archive item (nothing deleted), cleans up its own temp dirs.

Password: never logged; passed to 7z via `-p` (argv — acceptable on this single-user VPS).
Processes talk only through Postgres, so the password unavoidably transits a DB column briefly;
step 1's scrub-on-claim keeps that window to seconds.
"""

import asyncio
import os
import re
import shutil

from telethon.errors import FloodError  # base class → catches FLOOD_WAIT and FLOOD_PREMIUM_WAIT alike

from bot_config import PIKPAK_STAGING_DIR, PIKPAK_MAX_BYTES, DRIVE_SPLIT_PART_MB, log

SEVENZIP = os.environ.get("SEVENZIP_PATH", "7z")
UNPACK_STAGING = os.path.join(os.path.dirname(PIKPAK_STAGING_DIR), "_unpack")  # /staging/_unpack
POLL_INTERVAL = 4
_MEDIA_EXTS = {
    ".mp4", ".mkv", ".avi", ".mov", ".wmv", ".flv", ".webm", ".m4v", ".ts", ".3gp",
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".mp3", ".m4a", ".flac", ".wav", ".ogg",
}
_CONCAT_CHUNK = 8 * 1024 * 1024


class UnpackError(Exception):
    """A user-facing failure (message is safe to store in unpack_jobs.message)."""


def _is_media(fname: str) -> bool:
    return os.path.splitext(fname)[1].lower() in _MEDIA_EXTS


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------
async def ensure_schema(db):
    """Create unpack_jobs (+ NOTIFY) and requeue jobs stranded 'running' by a restart. Kept in sync
    with schema.sql."""
    await db.execute("""
        CREATE TABLE IF NOT EXISTS unpack_jobs (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id     BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            password    TEXT,
            status      TEXT NOT NULL DEFAULT 'queued'
                          CHECK (status IN ('queued','running','done','failed')),
            progress    INTEGER NOT NULL DEFAULT 0,
            message     TEXT,
            chat_id     BIGINT,
            message_id  BIGINT,
            created_at  TEXT NOT NULL DEFAULT now_text(),
            updated_at  TEXT NOT NULL DEFAULT now_text()
        )
    """)
    await db.execute("CREATE INDEX IF NOT EXISTS idx_unpack_jobs_status ON unpack_jobs(status)")
    await db.execute(
        "CREATE OR REPLACE FUNCTION notify_unpack_change() RETURNS trigger "
        "LANGUAGE plpgsql AS $func$ BEGIN "
        "PERFORM pg_notify('unpack_changed', TG_TABLE_NAME); RETURN NULL; END $func$"
    )
    await db.execute("DROP TRIGGER IF EXISTS trg_notify_unpack_jobs ON unpack_jobs")
    await db.execute(
        "CREATE TRIGGER trg_notify_unpack_jobs AFTER INSERT OR UPDATE OR DELETE ON unpack_jobs "
        "FOR EACH STATEMENT EXECUTE FUNCTION notify_unpack_change()"
    )
    # Stranded by a restart mid-run → requeue (the password is already gone; a re-run needs it again,
    # so mark failed instead of silently retrying without a password).
    await db.execute(
        "UPDATE unpack_jobs SET status='failed', message='interrupted by restart — re-run', "
        "updated_at=now_text() WHERE status='running'"
    )


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------
async def _set(db, jid, *, status=None, progress=None, message=None):
    cols, vals = [], []
    if status is not None:
        cols.append("status=?"); vals.append(status)
    if progress is not None:
        cols.append("progress=?"); vals.append(progress)
    if message is not None:
        cols.append("message=?"); vals.append(message[:400])
    cols.append("updated_at=now_text()")
    vals.append(jid)
    await db.execute(f"UPDATE unpack_jobs SET {', '.join(cols)} WHERE id=?", vals)


async def _claim(db):
    """Atomically claim the oldest queued job AND scrub its password in one statement. The CTE reads
    the password before the UPDATE nulls it, so RETURNING still hands us the original."""
    rs = await db.execute(
        "WITH claimed AS ("
        "  SELECT id, item_id, password, chat_id, message_id FROM unpack_jobs "
        "  WHERE status='queued' ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED) "
        "UPDATE unpack_jobs u SET status='running', password=NULL, progress=0, updated_at=now_text() "
        "FROM claimed WHERE u.id = claimed.id "
        "RETURNING claimed.id, claimed.item_id, claimed.password, claimed.chat_id, claimed.message_id"
    )
    if not rs.rows:
        return None
    r = rs.rows[0]
    return {"id": r[0], "item_id": r[1], "password": r[2], "chat_id": r[3], "message_id": r[4]}


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------
def _flood_secs(e) -> int:
    """Seconds to wait from a Telegram FloodError (FLOOD_PREMIUM_WAIT_N carries N in its text)."""
    s = getattr(e, "seconds", None)
    if s:
        return int(s)
    m = re.search(r"WAIT_(\d+)", str(e)) or re.search(r"(\d+)\s*second", str(e))
    return int(m.group(1)) if m else 30


async def _tg_retry(call, what):
    """Await a small Telethon call (e.g. get_messages), sleeping through flood-waits."""
    for attempt in range(12):
        try:
            return await call()
        except FloodError as e:
            wait = _flood_secs(e) + 2
            log.warning("Unpack: Telegram flood-wait %ss on %s (attempt %s/12)", wait, what, attempt + 1)
            await asyncio.sleep(wait)
    raise UnpackError(f"Telegram flood-limited {what} after repeated waits — try again later.")


async def _download_part(client, msg, path):
    """Download a message's file to `path`, resuming across Telegram flood-waits via chunked
    iter_download — so FLOOD_PREMIUM_WAIT on a large non-premium download waits and continues from the
    last byte instead of restarting the whole part from 0. Gives up only if it stops advancing."""
    with open(path, "wb") as f:
        offset, last, stuck = 0, 0, 0
        while True:
            try:
                async for chunk in client.iter_download(msg.media, offset=offset, request_size=512 * 1024):
                    f.write(chunk)
                    offset += len(chunk)
                return
            except FloodError as e:
                stuck = stuck + 1 if offset == last else 0
                last = offset
                if stuck > 30:
                    raise UnpackError("Telegram flood-limited the download and it stopped advancing.")
                secs = _flood_secs(e) + 1
                log.warning("Unpack: flood-wait %ss on part download at %s bytes", secs, offset)
                await asyncio.sleep(secs)
                f.seek(offset)  # resume from the last written byte


async def _download_and_concat(client, channel, db, item_id, workdir) -> str:
    """Download every part of the item from Telegram and concat in part order → the archive path."""
    # Let Telethon sleep through short flood-waits internally (resumes mid-download, no restart);
    # _tg_retry is the backstop for the premium variant if it isn't auto-handled.
    try:
        client.flood_sleep_threshold = max(int(getattr(client, "flood_sleep_threshold", 60) or 60), 300)
    except Exception:  # noqa: BLE001
        pass
    rs = await db.execute(
        "SELECT channel_msg_id, file_name FROM parts WHERE item_id = ? ORDER BY part_number, channel_msg_id",
        [item_id],
    )
    if not rs.rows:
        raise UnpackError("Item has no parts to unpack.")
    # Archive name = first part's name minus a trailing .NNN volume suffix, else a generic name.
    first_name = rs.rows[0][1] or "archive.7z"
    base = first_name
    if base.rsplit(".", 1)[-1].isdigit():
        base = base.rsplit(".", 1)[0]
    archive_path = os.path.join(workdir, os.path.basename(base) or "archive.bin")
    with open(archive_path, "wb") as out:
        for channel_msg_id, _fname in rs.rows:
            msg = await _tg_retry(
                lambda cid=channel_msg_id: client.get_messages(channel, ids=int(cid)), "message fetch")
            if not msg or not msg.media:
                raise UnpackError(f"Part message {channel_msg_id} is missing or has no file.")
            part_tmp = os.path.join(workdir, f"_part_{channel_msg_id}")
            await _download_part(client, msg, part_tmp)
            # Blocking file IO off the event loop so uploads/progress keep running. Delete each part
            # right after appending → peak disk ≈ archive so far + one part.
            await asyncio.to_thread(_append_and_drop, part_tmp, out)
    return archive_path


def _append_and_drop(part_tmp, out) -> None:
    with open(part_tmp, "rb") as f:
        shutil.copyfileobj(f, out, _CONCAT_CHUNK)
    os.remove(part_tmp)


async def _extract(archive_path, password, outdir) -> None:
    """7z-extract into outdir. `-p` is always passed (even empty) so 7z never waits on a prompt.
    Runs as an async subprocess so a long extraction doesn't block the watcher event loop."""
    os.makedirs(outdir, exist_ok=True)
    proc = await asyncio.create_subprocess_exec(
        SEVENZIP, "x", archive_path, f"-o{outdir}", "-y", "-p" + (password or ""),
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    if proc.returncode != 0:
        blob = (out.decode("utf-8", "replace") + err.decode("utf-8", "replace")).lower()
        if "wrong password" in blob or "encrypted" in blob or "data error" in blob:
            raise UnpackError("Extraction failed — wrong or missing password for this archive.")
        raise UnpackError(
            f"7z extraction failed (rc={proc.returncode}). {err.decode('utf-8', 'replace').strip()[:200]}")


async def _stage_outputs(db, outdir, unpacked_folder, jid) -> int:
    """Move each extracted file into its own staging dir and queue an upload_jobs row. Returns count."""
    staged = 0
    for root, _dirs, files in os.walk(outdir):
        for name in files:
            src = os.path.join(root, name)
            rel_dir = os.path.relpath(root, outdir)
            rel_dir = "" if rel_dir == "." else rel_dir.replace("\\", "/")
            size = os.path.getsize(src)
            kind = "media" if _is_media(name) else "archive"
            part_size = DRIVE_SPLIT_PART_MB if (kind == "archive" and size > PIKPAK_MAX_BYTES) else 4096
            # Title nests under "<archive> (unpacked)/<subdirs>/<name-without-ext>" — upsert_item splits
            # on '/' into folders, so the extracted tree is mirrored in the drive.
            base = os.path.splitext(name)[0] or name
            title = "/".join(p for p in [unpacked_folder, rel_dir, base] if p)
            job_dir = os.path.join(UNPACK_STAGING, str(jid), str(staged))
            os.makedirs(job_dir, exist_ok=True)
            shutil.move(src, os.path.join(job_dir, name))
            await db.execute(
                "INSERT INTO upload_jobs (kind, title, tags, source_path, part_size, origin, "
                "cleanup_source, total_bytes, status) VALUES (?, ?, '', ?, ?, 'upload', 1, ?, 'pending')",
                [kind, title, job_dir, part_size, size],
            )
            staged += 1
    return staged


async def _process(client, channel, db, job):
    jid, item_id = job["id"], job["item_id"]
    password = job.pop("password", None)  # local only; already NULLed in the DB by _claim
    workdir = os.path.join(UNPACK_STAGING, str(jid), "_work")
    outdir = os.path.join(UNPACK_STAGING, str(jid), "_out")
    try:
        rs = await db.execute("SELECT title, total_size FROM items WHERE id = ?", [item_id])
        if not rs.rows:
            raise UnpackError("Archive item not found.")
        title, total_size = rs.rows[0][0], int(rs.rows[0][1] or 0)

        # Disk-guard: archive + extracted output + staging (~3× the stored size) must fit.
        try:
            os.makedirs(UNPACK_STAGING, exist_ok=True)
            free = shutil.disk_usage(UNPACK_STAGING).free
        except OSError:
            free = None
        if free is not None and total_size and free < total_size * 3:
            raise UnpackError(
                f"Not enough disk to unpack '{title}' (~{total_size * 3 // 1048576} MB needed, "
                f"{free // 1048576} MB free). Free up space and retry.")

        os.makedirs(workdir, exist_ok=True)
        await _set(db, jid, progress=10, message="downloading parts…")
        archive_path = await _download_and_concat(client, channel, db, item_id, workdir)

        await _set(db, jid, progress=50, message="extracting…")
        _extract(archive_path, password, outdir)
        password = None  # done with it
        os.remove(archive_path)  # free the concatenated archive before staging outputs

        await _set(db, jid, progress=85, message="storing extracted files…")
        n = await _stage_outputs(db, outdir, f"{title} (unpacked)", jid)
        if n == 0:
            raise UnpackError("Archive extracted but contained no files.")

        await _set(db, jid, status="done", progress=100,
                   message=f"{n} file(s) extracted — uploading to the drive…")
        log.info("Unpack job #%s: item %s → %s file(s) queued for upload", jid, item_id, n)
    except UnpackError as e:
        await _set(db, jid, status="failed", message=str(e))
        log.warning("Unpack job #%s failed: %s", jid, e)
    except Exception as e:  # noqa: BLE001
        await _set(db, jid, status="failed", message=f"unexpected error: {str(e)[:200]}")
        log.exception("Unpack job #%s crashed", jid)
    finally:
        password = None
        # Remove work/extract temp dirs; the per-file staging dirs are cleaned by the watcher upload.
        shutil.rmtree(workdir, ignore_errors=True)
        shutil.rmtree(outdir, ignore_errors=True)


# ---------------------------------------------------------------------------
# Worker loop (spawned from watcher.main)
# ---------------------------------------------------------------------------
async def worker_loop(client, channel, db):
    log.info("Unpack worker started")
    while True:
        try:
            job = await _claim(db)
            if job:
                await _process(client, channel, db, job)
            else:
                await asyncio.sleep(POLL_INTERVAL)
        except asyncio.CancelledError:
            raise
        except Exception as e:  # noqa: BLE001
            log.warning("Unpack worker loop error: %s", e)
            await asyncio.sleep(POLL_INTERVAL)
