"""Archive-unpack worker — extract a stored multi-part archive item and re-store its contents as
normal (streamable) items, so e.g. a video inside a password-protected 7z can be watched in-app
without downloading the whole archive locally.

Runs INSIDE the watcher process (the only one with both the Telethon client and p7zip). The web
inserts an `unpack_jobs` row (item_id + optional password); this worker:
  1. claims the job and SCRUBS the password — reads it into a local var and NULLs the column in the
     same statement, so it never lingers in the DB (only the seconds between insert and claim),
  2. downloads every part of the item from Telegram and concatenates them in part order → the archive
     (plain ordered concat reconstructs both 7z-native multi-volumes and raw binary splits),
  3. 7z-extracts it (with the password if encrypted; `-p` is always passed so 7z never blocks on an
     interactive prompt),
  4. inserts one `upload_jobs` row per extracted file (origin='upload', cleanup_source=1) → the
     existing watcher pipeline uploads them and the bot indexes them (video → streamable media item),
  5. keeps the original archive item (nothing deleted), cleans up its own temp dirs.

Password: never logged; passed to 7z via `-p` (argv — acceptable on this single-user VPS).
Processes talk only through Postgres, so the password unavoidably transits a DB column briefly;
step 1's scrub-on-claim keeps that window to seconds.
"""

import asyncio
import os
import re
import shutil
import time

from telethon.errors import FloodError  # base class → catches FLOOD_WAIT and FLOOD_PREMIUM_WAIT alike

from bot_config import PIKPAK_STAGING_DIR, PIKPAK_MAX_BYTES, DRIVE_SPLIT_PART_MB, log

SEVENZIP = os.environ.get("SEVENZIP_PATH", "7z")
UNPACK_STAGING = os.path.join(os.path.dirname(PIKPAK_STAGING_DIR), "_unpack")  # /staging/_unpack
# Concatenated archives are cached here keyed by item_id so a retry after a wrong password re-extracts
# WITHOUT re-downloading all the parts. A cache entry is deleted on success and swept after CACHE_TTL_S
# (default 48h) if you give up — so it never leaks disk indefinitely.
UNPACK_CACHE = os.path.join(UNPACK_STAGING, "_cache")
CACHE_TTL_S = int(os.environ.get("UNPACK_CACHE_TTL_H", "48")) * 3600
POLL_INTERVAL = 4
_MEDIA_EXTS = {
    ".mp4", ".mkv", ".avi", ".mov", ".wmv", ".flv", ".webm", ".m4v", ".ts", ".3gp",
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".mp3", ".m4a", ".flac", ".wav", ".ogg",
}
_CONCAT_CHUNK = 8 * 1024 * 1024
# Nested extraction: some archives hide another (password-protected) archive inside a file disguised
# as an image (e.g. a RAR appended to a .jpg). 7z detects archives by content signature, not
# extension, so we can peel these layers automatically when a password is given, up to this depth.
UNPACK_MAX_DEPTH = int(os.environ.get("UNPACK_MAX_DEPTH", "4"))
# zip-based files that are really documents/apps — never recurse into these even if 7z can open them.
_SKIP_RECURSE_EXTS = {".docx", ".xlsx", ".pptx", ".odt", ".ods", ".odp", ".apk", ".jar", ".epub",
                      ".ipa", ".whl", ".crx", ".zipx"}


class UnpackError(Exception):
    """A user-facing failure (message is safe to store in unpack_jobs.message)."""


class BadPassword(UnpackError):
    """Extraction failed because the archive password was wrong/missing — the cached archive is kept
    so a retry with the right password skips the re-download."""


def _is_media(fname: str) -> bool:
    return os.path.splitext(fname)[1].lower() in _MEDIA_EXTS


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------
async def ensure_schema(db):
    """Create unpack_jobs (+ NOTIFY) and requeue jobs stranded 'running' by a restart. Kept in sync
    with schema.sql."""
    await db.execute("""
        CREATE TABLE IF NOT EXISTS unpack_jobs (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            item_id     BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            password    TEXT,
            status      TEXT NOT NULL DEFAULT 'queued'
                          CHECK (status IN ('queued','running','done','failed')),
            progress    INTEGER NOT NULL DEFAULT 0,
            message     TEXT,
            chat_id     BIGINT,
            message_id  BIGINT,
            created_at  TEXT NOT NULL DEFAULT now_text(),
            updated_at  TEXT NOT NULL DEFAULT now_text()
        )
    """)
    await db.execute("CREATE INDEX IF NOT EXISTS idx_unpack_jobs_status ON unpack_jobs(status)")
    await db.execute(
        "CREATE OR REPLACE FUNCTION notify_unpack_change() RETURNS trigger "
        "LANGUAGE plpgsql AS $func$ BEGIN "
        "PERFORM pg_notify('unpack_changed', TG_TABLE_NAME); RETURN NULL; END $func$"
    )
    await db.execute("DROP TRIGGER IF EXISTS trg_notify_unpack_jobs ON unpack_jobs")
    await db.execute(
        "CREATE TRIGGER trg_notify_unpack_jobs AFTER INSERT OR UPDATE OR DELETE ON unpack_jobs "
        "FOR EACH STATEMENT EXECUTE FUNCTION notify_unpack_change()"
    )
    # Stranded by a restart mid-run → requeue (the password is already gone; a re-run needs it again,
    # so mark failed instead of silently retrying without a password).
    await db.execute(
        "UPDATE unpack_jobs SET status='failed', message='interrupted by restart — re-run', "
        "updated_at=now_text() WHERE status='running'"
    )


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------
async def _set(db, jid, *, status=None, progress=None, message=None):
    cols, vals = [], []
    if status is not None:
        cols.append("status=?"); vals.append(status)
    if progress is not None:
        cols.append("progress=?"); vals.append(progress)
    if message is not None:
        cols.append("message=?"); vals.append(message[:400])
    cols.append("updated_at=now_text()")
    vals.append(jid)
    await db.execute(f"UPDATE unpack_jobs SET {', '.join(cols)} WHERE id=?", vals)


async def _claim(db):
    """Atomically claim the oldest queued job AND scrub its password in one statement. The CTE reads
    the password before the UPDATE nulls it, so RETURNING still hands us the original."""
    rs = await db.execute(
        "WITH claimed AS ("
        "  SELECT id, item_id, password, chat_id, message_id FROM unpack_jobs "
        "  WHERE status='queued' ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED) "
        "UPDATE unpack_jobs u SET status='running', password=NULL, progress=0, updated_at=now_text() "
        "FROM claimed WHERE u.id = claimed.id "
        "RETURNING claimed.id, claimed.item_id, claimed.password, claimed.chat_id, claimed.message_id"
    )
    if not rs.rows:
        return None
    r = rs.rows[0]
    return {"id": r[0], "item_id": r[1], "password": r[2], "chat_id": r[3], "message_id": r[4]}


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------
def _flood_secs(e) -> int:
    """Seconds to wait from a Telegram FloodError (FLOOD_PREMIUM_WAIT_N carries N in its text)."""
    s = getattr(e, "seconds", None)
    if s:
        return int(s)
    m = re.search(r"WAIT_(\d+)", str(e)) or re.search(r"(\d+)\s*second", str(e))
    return int(m.group(1)) if m else 30


async def _tg_retry(call, what):
    """Await a small Telethon call (e.g. get_messages), sleeping through flood-waits."""
    for attempt in range(12):
        try:
            return await call()
        except FloodError as e:
            wait = _flood_secs(e) + 2
            log.warning("Unpack: Telegram flood-wait %ss on %s (attempt %s/12)", wait, what, attempt + 1)
            await asyncio.sleep(wait)
    raise UnpackError(f"Telegram flood-limited {what} after repeated waits — try again later.")


async def _download_part(client, msg, path):
    """Download a message's file to `path`, resuming across Telegram flood-waits via chunked
    iter_download — so FLOOD_PREMIUM_WAIT on a large non-premium download waits and continues from the
    last byte instead of restarting the whole part from 0. Gives up only if it stops advancing."""
    with open(path, "wb") as f:
        offset, last, stuck = 0, 0, 0
        while True:
            try:
                async for chunk in client.iter_download(msg.media, offset=offset, request_size=512 * 1024):
                    f.write(chunk)
                    offset += len(chunk)
                return
            except FloodError as e:
                stuck = stuck + 1 if offset == last else 0
                last = offset
                if stuck > 30:
                    raise UnpackError("Telegram flood-limited the download and it stopped advancing.")
                secs = _flood_secs(e) + 1
                log.warning("Unpack: flood-wait %ss on part download at %s bytes", secs, offset)
                await asyncio.sleep(secs)
                f.seek(offset)  # resume from the last written byte


async def _download_and_concat(client, channel, db, jid, item_id, workdir) -> str:
    """Download every part of the item from Telegram and concat in part order → the archive path.
    Reports coarse progress (10→45%) across parts on unpack_jobs so the web shows movement."""
    # Let Telethon sleep through short flood-waits internally (resumes mid-download, no restart);
    # _tg_retry is the backstop for the premium variant if it isn't auto-handled.
    try:
        client.flood_sleep_threshold = max(int(getattr(client, "flood_sleep_threshold", 60) or 60), 300)
    except Exception:  # noqa: BLE001
        pass
    rs = await db.execute(
        "SELECT channel_msg_id, file_name FROM parts WHERE item_id = ? ORDER BY part_number, channel_msg_id",
        [item_id],
    )
    if not rs.rows:
        raise UnpackError("Item has no parts to unpack.")
    total = len(rs.rows)
    # Archive name = first part's name minus a trailing .NNN volume suffix, else a generic name.
    first_name = rs.rows[0][1] or "archive.7z"
    base = first_name
    if base.rsplit(".", 1)[-1].isdigit():
        base = base.rsplit(".", 1)[0]
    archive_path = os.path.join(workdir, os.path.basename(base) or "archive.bin")
    with open(archive_path, "wb") as out:
        for i, (channel_msg_id, _fname) in enumerate(rs.rows, start=1):
            await _set(db, jid, progress=10 + int(35 * (i - 1) / total),
                       message=f"downloading part {i}/{total}…")
            msg = await _tg_retry(
                lambda cid=channel_msg_id: client.get_messages(channel, ids=int(cid)), "message fetch")
            if not msg or not msg.media:
                raise UnpackError(f"Part message {channel_msg_id} is missing or has no file.")
            part_tmp = os.path.join(workdir, f"_part_{channel_msg_id}")
            await _download_part(client, msg, part_tmp)
            # Blocking file IO off the event loop so uploads/progress keep running. Delete each part
            # right after appending → peak disk ≈ archive so far + one part.
            await asyncio.to_thread(_append_and_drop, part_tmp, out)
    return archive_path


def _append_and_drop(part_tmp, out) -> None:
    with open(part_tmp, "rb") as f:
        shutil.copyfileobj(f, out, _CONCAT_CHUNK)
    os.remove(part_tmp)


async def _extract(archive_path, password, outdir) -> None:
    """7z-extract into outdir. `-p` is always passed (even empty) so 7z never waits on a prompt.
    Runs as an async subprocess so a long extraction doesn't block the watcher event loop."""
    os.makedirs(outdir, exist_ok=True)
    proc = await asyncio.create_subprocess_exec(
        SEVENZIP, "x", archive_path, f"-o{outdir}", "-y", "-p" + (password or ""),
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    if proc.returncode != 0:
        blob = (out.decode("utf-8", "replace") + err.decode("utf-8", "replace")).lower()
        if "wrong password" in blob or "encrypted" in blob or "data error" in blob:
            raise BadPassword("Extraction failed — wrong or missing password for this archive.")
        raise UnpackError(
            f"7z extraction failed (rc={proc.returncode}). {err.decode('utf-8', 'replace').strip()[:200]}")


async def _is_archive(path, pw) -> bool:
    """True if 7z can open `path` as an archive by content signature (so a RAR appended to a .jpg
    counts). `7z l` returns rc 0 for an archive, rc 2 for a normal file."""
    proc = await asyncio.create_subprocess_exec(
        SEVENZIP, "l", "-p" + (pw or ""), "-y", path,
        stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL,
    )
    await proc.wait()
    return proc.returncode == 0


async def _deep_extract(outdir, pw):
    """Peel nested / disguised archives: repeatedly find extracted files that are themselves archives
    (e.g. a password-protected RAR hidden inside a .jpg) and extract them in place, dropping the
    container, up to UNPACK_MAX_DEPTH passes. A wrong password on an inner layer raises BadPassword so
    the cached outer archive is kept for a retry; a file 7z opens but can't extract is left as a leaf."""
    for _pass in range(UNPACK_MAX_DEPTH):
        found = False
        targets = [os.path.join(r, n) for r, _d, files in os.walk(outdir) for n in files]
        for fpath in targets:
            if not os.path.exists(fpath) or os.path.splitext(fpath)[1].lower() in _SKIP_RECURSE_EXTS:
                continue
            if not await _is_archive(fpath, pw):
                continue
            tmp = fpath + ".x"
            try:
                await _extract(fpath, pw, tmp)
            except BadPassword:
                shutil.rmtree(tmp, ignore_errors=True)
                raise
            except UnpackError:
                shutil.rmtree(tmp, ignore_errors=True)
                continue
            os.remove(fpath)  # drop the container / decoy image
            parent = os.path.dirname(fpath)
            for n2 in os.listdir(tmp):
                dst = os.path.join(parent, n2)
                if os.path.exists(dst):
                    stem, ext = os.path.splitext(n2)
                    dst = os.path.join(parent, f"{stem}_{_pass}{ext}")
                shutil.move(os.path.join(tmp, n2), dst)
            shutil.rmtree(tmp, ignore_errors=True)
            found = True
        if not found:
            break


async def _stage_outputs(db, outdir, unpacked_folder, jid) -> int:
    """Move each extracted file into its own staging dir and queue an upload_jobs row. Returns count."""
    staged = 0
    for root, _dirs, files in os.walk(outdir):
        for name in files:
            src = os.path.join(root, name)
            rel_dir = os.path.relpath(root, outdir)
            rel_dir = "" if rel_dir == "." else rel_dir.replace("\\", "/")
            size = os.path.getsize(src)
            kind = "media" if _is_media(name) else "archive"
            part_size = DRIVE_SPLIT_PART_MB if (kind == "archive" and size > PIKPAK_MAX_BYTES) else 4096
            # Title nests under "<archive> (unpacked)/<subdirs>/<name-without-ext>" — upsert_item splits
            # on '/' into folders, so the extracted tree is mirrored in the drive.
            base = os.path.splitext(name)[0] or name
            title = "/".join(p for p in [unpacked_folder, rel_dir, base] if p)
            job_dir = os.path.join(UNPACK_STAGING, str(jid), str(staged))
            os.makedirs(job_dir, exist_ok=True)
            shutil.move(src, os.path.join(job_dir, name))
            await db.execute(
                "INSERT INTO upload_jobs (kind, title, tags, source_path, part_size, origin, "
                "cleanup_source, total_bytes, status) VALUES (?, ?, '', ?, ?, 'upload', 1, ?, 'pending')",
                [kind, title, job_dir, part_size, size],
            )
            staged += 1
    return staged


async def _process(client, channel, db, job):
    jid, item_id = job["id"], job["item_id"]
    password = job.pop("password", None)  # local only; already NULLed in the DB by _claim
    workdir = os.path.join(UNPACK_STAGING, str(jid), "_work")
    outdir = os.path.join(UNPACK_STAGING, str(jid), "_out")
    cache_path = os.path.join(UNPACK_CACHE, str(item_id))  # concatenated archive, reused across retries
    try:
        rs = await db.execute("SELECT title, total_size FROM items WHERE id = ?", [item_id])
        if not rs.rows:
            raise UnpackError("Archive item not found.")
        title, total_size = rs.rows[0][0], int(rs.rows[0][1] or 0)

        os.makedirs(UNPACK_CACHE, exist_ok=True)
        os.makedirs(workdir, exist_ok=True)
        cached = os.path.exists(cache_path) and (not total_size or os.path.getsize(cache_path) == total_size)
        if cached:
            # A previous run already downloaded + concatenated this archive (e.g. a wrong-password
            # retry) — re-extract straight from the cache, no re-download.
            await _set(db, jid, progress=48, message="using cached archive…")
            archive_path = cache_path
        else:
            # Disk-guard: archive + extracted output + staging (~3× the stored size) must fit.
            try:
                os.makedirs(UNPACK_STAGING, exist_ok=True)
                free = shutil.disk_usage(UNPACK_STAGING).free
            except OSError:
                free = None
            if free is not None and total_size and free < total_size * 3:
                raise UnpackError(
                    f"Not enough disk to unpack '{title}' (~{total_size * 3 // 1048576} MB needed, "
                    f"{free // 1048576} MB free). Free up space and retry.")
            tmp = await _download_and_concat(client, channel, db, jid, item_id, workdir)
            shutil.move(tmp, cache_path)  # cache the concatenated archive for any retry
            archive_path = cache_path

        await _set(db, jid, progress=50, message="extracting…")
        await _extract(archive_path, password, outdir)
        # Peel any nested/disguised inner archive (e.g. a password-protected RAR hidden in a .jpg).
        # Gated on a password: that's the signal the user wants the protected inner content.
        if password:
            await _set(db, jid, progress=70, message="extracting nested archive…")
            await _deep_extract(outdir, password)
        password = None  # done with it

        await _set(db, jid, progress=85, message="storing extracted files…")
        n = await _stage_outputs(db, outdir, f"{title} (unpacked)", jid)
        if n == 0:
            raise UnpackError("Archive extracted but contained no files.")

        _rm(cache_path)  # success → the cached archive is no longer needed
        await _set(db, jid, status="done", progress=100,
                   message=f"{n} file(s) extracted — uploading to the drive…")
        log.info("Unpack job #%s: item %s → %s file(s) queued for upload", jid, item_id, n)
    except BadPassword as e:
        # Keep the cached archive so a retry with the right password skips the re-download.
        await _set(db, jid, status="failed",
                   message=str(e) + " (archive cached — a retry won't re-download; it's auto-cleared in "
                                    f"{CACHE_TTL_S // 3600}h if you give up).")
        log.warning("Unpack job #%s: bad password (archive cached)", jid)
    except UnpackError as e:
        _rm(cache_path)  # a non-password failure won't be helped by the cache
        await _set(db, jid, status="failed", message=str(e))
        log.warning("Unpack job #%s failed: %s", jid, e)
    except Exception as e:  # noqa: BLE001
        _rm(cache_path)
        await _set(db, jid, status="failed", message=f"unexpected error: {str(e)[:200]}")
        log.exception("Unpack job #%s crashed", jid)
    finally:
        password = None
        # Remove work/extract temp dirs; the per-file staging dirs are cleaned by the watcher upload.
        shutil.rmtree(workdir, ignore_errors=True)
        shutil.rmtree(outdir, ignore_errors=True)


def _rm(path):
    try:
        os.remove(path)
    except OSError:
        pass


def _sweep_cache():
    """Delete cached archives older than CACHE_TTL_S — abandoned password attempts don't leak disk."""
    try:
        entries = os.listdir(UNPACK_CACHE)
    except OSError:
        return
    for n in entries:
        p = os.path.join(UNPACK_CACHE, n)
        try:
            if os.path.isfile(p) and time.time() - os.path.getmtime(p) > CACHE_TTL_S:
                os.remove(p)
                log.info("Unpack: swept stale cached archive %s", n)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Worker loop (spawned from watcher.main)
# ---------------------------------------------------------------------------
async def worker_loop(client, channel, db):
    log.info("Unpack worker started")
    while True:
        try:
            job = await _claim(db)
            if job:
                await _process(client, channel, db, job)
            else:
                _sweep_cache()  # opportunistic: clear abandoned cached archives while idle
                await asyncio.sleep(POLL_INTERVAL)
        except asyncio.CancelledError:
            raise
        except Exception as e:  # noqa: BLE001
            log.warning("Unpack worker loop error: %s", e)
            await asyncio.sleep(POLL_INTERVAL)
